# Generated by Django 6.0.3 on 2026-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0076_certificationcourse_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippbl',
            name='domain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mentormenteeinteraction',
            name='week',
            field=models.CharField(blank=True, choices=[('Interaction-1', 'Interaction-1'), ('Interaction-2', 'Interaction-2'), ('Interaction-3', 'Interaction-3'), ('Interaction-4', 'Interaction-4'), ('Interaction-5', 'Interaction-5'), ('Interaction-6', 'Interaction-6'), ('Interaction-7', 'Interaction-7'), ('Interaction-8', 'Interaction-8'), ('Interaction-9', 'Interaction-9'), ('Interaction-10', 'Interaction-10'), ('Interaction-11', 'Interaction-11'), ('Interaction-12', 'Interaction-12')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='div',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('unverified', 'Unverified'), ('verify your document manually', 'verify your document manually')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='weeklyagenda',
            name='week',
            field=models.CharField(blank=True, choices=[('Interaction-1', 'Interaction-1'), ('Interaction-2', 'Interaction-2'), ('Interaction-3', 'Interaction-3'), ('Interaction-4', 'Interaction-4'), ('Interaction-5', 'Interaction-5'), ('Interaction-6', 'Interaction-6'), ('Interaction-7', 'Interaction-7'), ('Interaction-8', 'Interaction-8'), ('Interaction-9', 'Interaction-9'), ('Interaction-10', 'Interaction-10'), ('Interaction-11', 'Interaction-11'), ('Interaction-12', 'Interaction-12')], max_length=15, null=True),
        ),
    ]
