# Generated by Django 6.0.3 on 2026-03-31 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0077_internshippbl_domain_mentormenteeinteraction_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWOTAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('moodle_id', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.CharField(blank=True, choices=[('Batch-1', 'Batch-1'), ('Batch-2', 'Batch-2'), ('Batch-3', 'Batch-3')], max_length=50, null=True)),
                ('mentor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('career_option', models.CharField(blank=True, choices=[('higher_studies', 'Higher Studies'), ('entrepreneurship', 'Entrepreneurship'), ('placement', 'On-campus Placement'), ('other', 'Other')], max_length=50, null=True)),
                ('other_career', models.CharField(blank=True, max_length=200, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('opportunities', models.TextField(blank=True, null=True)),
                ('threats', models.TextField(blank=True, null=True)),
                ('ppt_confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10, null=True)),
                ('ppt_remark', models.TextField(blank=True, null=True)),
                ('core_subjects_confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10, null=True)),
                ('core_subjects_remark', models.TextField(blank=True, null=True)),
                ('communication_confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10, null=True)),
                ('communication_other', models.CharField(blank=True, max_length=200, null=True)),
                ('communication_remark', models.TextField(blank=True, null=True)),
                ('softskills_confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10, null=True)),
                ('softskills_remark', models.TextField(blank=True, null=True)),
                ('resume_building_confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10, null=True)),
                ('resume_remark', models.TextField(blank=True, null=True)),
                ('project_explanation_confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10, null=True)),
                ('project_remark', models.TextField(blank=True, null=True)),
                ('tech_platform_confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10, null=True)),
                ('higher_studies_confidence', models.CharField(blank=True, choices=[('na', 'Not Applicable'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True)),
                ('higher_studies_remark', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('support_needed', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
