# Generated by Django 6.0.3 on 2026-03-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0078_swotanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swotanalysis',
            name='communication_other',
        ),
    ]
