# Generated by Django 6.0.3 on 2026-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0080_internshippbl_qr_detected_internshippbl_qr_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationcourse',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('verify_physically', 'Verify Physically')], default='verify_physically', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='internshippbl',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('verify_physically', 'Verify Physically')], default='verify_physically', max_length=20, null=True),
        ),
    ]
