# Generated by Django 6.0 on 2026-04-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0081_alter_certificationcourse_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationcourse',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='internshippbl',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otherevent',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paperpublication',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportsculturalevent',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyagenda',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28')], max_length=20, null=True),
        ),
    ]
